#!/bin/bash

echo "Building..."
docker build -t crawlr/landing .
echo "Running Docker container!"
docker run -p 80:8000 -e GUROBI_HOME=/opt/gurobi701/linux64 -e PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/gurobi701/linux64/bin -e LD_LIBRARY_PATH=/opt/gurobi701/linux64/lib -d crawlr/landing tail -f /dev/null

DID=$(docker ps -f "ancestor=crawlr/landing" | tail -n+2 | cut -d" " -f1)

docker exec -d $DID uwsgi --socket /tmp/uwsgi.sock --chdir /crawlrProject --module crawlrProject.wsgi --chmod-socket=666

docker exec $DID nginx
