# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_neg', models.CharField(max_length=50)),
                ('fb_pos', models.CharField(max_length=50)),
                ('fb_date', models.DateField()),
            ],
        ),
    ]
